[package]
name = "thiserror-ext"
version = "0.1.0"
edition = "2021"
authors = ["Bugen Zhao <i@bugenzhao.com>"]
description = "Extensions to `thiserror` crate."
repository = "https://github.com/risingwavelabs/thiserror-ext"
keywords = []                                             # TODO
categories = []                                           # TODO
license = "Apache-2.0"

[dependencies]
thiserror = "1"
thiserror-ext-derive = { version = "=0.1.0", path = "derive" }

[workspace]
members = ["derive"]
